### ISSUE TITLE
Text has low contrast/brightness w.r.t background

### ISSUE THREAD

**Issue by quoraquestions** [romainl/vim-dichromatic#1]
![img](https://cloud.githubusercontent.com/assets/6267485/9983201/6ef321a0-5fa9-11e5-93cd-afd0807ba9cd.png)

**Comment by romainl** [comment]
The latest commit should fix a few things.

Note that vim-dichromatic currently only supports GVim/MacVim and 256color terminal emulators so make sure both tmux and your terminal emulator are set up correctly.

**Comment by quoraquestions** [comment]
The screenshot i shared with you is for screen-256. Thanks again will report back if it works for me

**Comment by romainl** [comment]
Cool.

Be careful, I'm moving everything to the "wip" branch until Dichromatic is more stable. Next push will remove everything but the README from "master".

**Comment by quoraquestions** [comment]
It is much better now, using this over a remote desktop session will comment more about contrast when i login from local network..

![img](https://cloud.githubusercontent.com/assets/6267485/10005006/876aa04e-6069-11e5-8477-9e3bc98c6646.png)
